language: node_js

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

script:
  - npm run eslint
  - npm run test-cov

after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls

before_deploy:
  - npm run jsdoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    tags: true
    node: "10"
  local_dir: docs
  name: "Tommy Chen"
  email: tommy351@gmail.com
